---
all:
  vars:
    mackerel_apikey: "{{ lookup('community.general.onepassword', '27sdvelavjp5v4p2e27qamxvfu', field='routers') }}"
  hosts:
    localhost:
      ansible_connection: local
    nono:
      ansible_host: nono
      ansible_user: tosuke
    erlite:
      ansible_host: erlite
      ansible_user: admin
    border:
      ansible_host: border
      ansible_user: me
  children:
    routers:
      hosts:
        nono:
        erlite:
        border:
    # OS
    vyos:
      hosts:
        nono:
        border:
    edgeos:
      hosts:
        erlite:
    # Location
    home:
      hosts:
        nono:
        erlite:
    home_primary:
      hosts:
        nono:
    home_secondsry:
      hosts:
        erlite:
    linode:
      hosts:
        border:
