nono:
  properties:
    nopasswd_sudo: true
    run_list:
      - recipes/nono.rb

border:
  properties:
    nopasswd_sudo: true
    run_list:
      - recipes/border.rb

erlite:
  properties:
    nopasswd_sudo: true
    run_list:
      - default.rb
