global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: litestream
    static_configs:
      - targets: ["litestream:9090"]

  - job_name: node
    proxy_from_environment: true
    static_configs:
      - targets:
        - "host.containers.internal:9100"
        - "border:9100"
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):\d+'
        replacement: "$1"
        target_label: instance
      - source_labels: [instance]
        regex: "host.containers.internal"
        replacement: "nono"
        target_label: instance
  - job_name: ix2105-if_mib
    static_configs:
      - targets:
          - "192.168.41.2"
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: ix2105
      - target_label: __address__
        replacement: snmp-exporter:9116
  - job_name: ix2105-nec_ix
    static_configs:
      - targets:
          - "192.168.41.2"
    metrics_path: /snmp
    params:
      module: [nec_ix]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: ix2105
      - target_label: __address__
        replacement: snmp-exporter:9116

  - job_name: frr
    proxy_from_environment: true
    static_configs:
      - targets:
        - "host.containers.internal:9342"
        - "border:9342"
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):\d+'
        replacement: "$1"
        target_label: instance
      - source_labels: [instance]
        regex: "host.containers.internal"
        replacement: "nono"
        target_label: instance
   