server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
- url: https://logs-prod-020.grafana.net/loki/api/v1/push
  basic_auth:
    username: ${GCLOUD_HOSTED_LOGS_ID}
    password: ${GCLOUD_RW_API_KEY}

scrape_configs:
- job_name: system
  static_configs:
  - targets: ["localhost"]
    labels:
      job: varlogs
      instance: <%= node['hostname'] %>
      __path__: /var/log/*log
  pipeline_stages:
  # Parse rsyslog messages
  - match:
      selector: '{filename="/var/log/auth.log"}'
      stages:
      - regex:
          expression: '^(?P<time>[^ ]*) (?P<host>[^ ]*) (?P<program>[^ \[]*)[^:]*: (?P<message>.*)'
      - labels:
          program:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: message

- job_name: journal
  journal:
    max_age: 12h
    path: <%= node['promtail']['journal_path'] %>
    labels:
      job: systemd-journal
      instance: <%= node['hostname'] %>
  relabel_configs:
  - source_labels: ['__journal__systemd_unit']
    target_label: 'unit'
  - action: drop
    regex: '.*tailscale.*'
    source_labels: ['__journal__systemd_unit', 'unit']
  - action: drop
    regex: '.*keepalived.*'
    source_labels: ['__journal__systemd_unit', 'unit']

